# Generated by Django 5.2.15 on 2026-06-24 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('defender', 'Defender'), ('investigator', 'Investigator'), ('mentor', 'Mentor')], max_length=30)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=20)),
                ('description_ru', models.TextField()),
                ('description_uz', models.TextField()),
                ('model_key', models.CharField(max_length=100, unique=True)),
                ('color_primary', models.CharField(default='#2563eb', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='GameMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('title_ru', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200)),
                ('scene_key', models.CharField(max_length=100)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('max_score', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ('scenario__order', 'difficulty', 'title_ru'),
            },
        ),
        migrations.CreateModel(
            name='GameScenario3D',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title_ru', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
                ('description_uz', models.TextField()),
                ('category', models.CharField(choices=[('phishing', 'Phishing'), ('social_engineering', 'Social engineering'), ('password_safety', 'Password safety'), ('account_security', 'Account security'), ('privacy_protection', 'Privacy protection'), ('safe_clicking', 'Safe clicking'), ('suspicious_login', 'Suspicious login')], max_length=40)),
                ('is_default', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'title_ru'),
            },
        ),
        migrations.CreateModel(
            name='GameMissionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('task_type', models.CharField(choices=[('select_object', 'Select object'), ('dialogue', 'Dialogue'), ('secure_account', 'Secure account')], max_length=40)),
                ('prompt_ru', models.TextField()),
                ('prompt_uz', models.TextField()),
                ('correct_value', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=10)),
                ('penalty', models.IntegerField(default=-5)),
                ('feedback_correct_ru', models.TextField()),
                ('feedback_correct_uz', models.TextField()),
                ('feedback_wrong_ru', models.TextField()),
                ('feedback_wrong_uz', models.TextField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='webgame.gamemission')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='gamemission',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='webgame.gamescenario3d'),
        ),
        migrations.CreateModel(
            name='GameSession3D',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('points_awarded', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webgame.gamecharacter')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webgame.gamemission')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webgame.gamescenario3d')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webgame_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_value', models.CharField(max_length=300)),
                ('correct', models.BooleanField()),
                ('points_delta', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webgame.gamemissionstep')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='webgame.gamesession3d')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserGameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('missions_completed', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('selected_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webgame.gamecharacter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webgame_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-total_score', 'user_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='gamemissionstep',
            constraint=models.UniqueConstraint(fields=('mission', 'order'), name='unique_webgame_step_order'),
        ),
        migrations.AddConstraint(
            model_name='gamemission',
            constraint=models.UniqueConstraint(fields=('scenario', 'difficulty'), name='unique_webgame_mission_per_difficulty'),
        ),
        migrations.AddConstraint(
            model_name='gameaction',
            constraint=models.UniqueConstraint(fields=('session', 'step'), name='one_webgame_action_per_step'),
        ),
    ]
