# Generated by Django 5.2.15 on 2026-06-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemissionstep',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
