# Generated by Django 5.2.15 on 2026-06-19 08:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScammerNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_hash', models.CharField(max_length=64, unique=True)),
                ('phone_encrypted', models.TextField()),
                ('phone_masked', models.CharField(max_length=13)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('suspicious', 'Suspicious'), ('scammer', 'Scammer'), ('verified_scammer', 'Verified scammer')], default='reported', max_length=20)),
                ('approved_reports_count', models.PositiveIntegerField(default=0)),
                ('first_reported_at', models.DateTimeField(blank=True, null=True)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_scammer_numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scam_type', models.CharField(choices=[('bank_call', 'Fake bank call'), ('sms_code', 'SMS code theft'), ('malware', 'Malicious application'), ('marketplace', 'Marketplace fraud'), ('prize', 'Fake prize'), ('relative', 'Fake relative'), ('romance', 'Romance scam'), ('investment', 'Investment scam'), ('other', 'Other')], max_length=30)),
                ('incident_date', models.DateField()),
                ('story', models.TextField(max_length=1000)),
                ('region', models.CharField(max_length=30)),
                ('damage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('moderator_comment', models.CharField(blank=True, max_length=500)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_scammer_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scammer_reports', to=settings.AUTH_USER_MODEL)),
                ('scammer_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='scammer_db.scammernumber')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='scammer_db__status_ae70fb_idx'), models.Index(fields=['scam_type', '-created_at'], name='scammer_db__scam_ty_3f1041_idx'), models.Index(fields=['region', '-created_at'], name='scammer_db__region_d310a1_idx')],
            },
        ),
    ]
