# Generated by Django 5.2.15 on 2026-07-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammer_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreport',
            name='target_type',
            field=models.CharField(choices=[('phone', 'Phone number'), ('url', 'Website or link'), ('account', 'Messenger or social account'), ('card', 'Card or bank account'), ('other', 'Other')], default='phone', max_length=20),
        ),
        migrations.AddField(
            model_name='communityreport',
            name='target_value',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='communityreport',
            name='scammer_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='scammer_db.scammernumber'),
        ),
    ]
