# Generated by Django 5.2.15 on 2026-06-19 11:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('category', models.CharField(choices=[('phishing', 'Phishing'), ('malware', 'Malware'), ('scam', 'Scam'), ('fake_bank', 'Fake bank')], max_length=20)),
                ('source', models.CharField(default='CyberSafe', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('content_type', models.CharField(choices=[('url', 'URL'), ('sms', 'SMS')], max_length=10)),
                ('verdict', models.CharField(choices=[('safe', 'No obvious risk detected'), ('suspicious', 'Suspicious'), ('dangerous', 'Dangerous')], max_length=12)),
                ('risk_score', models.PositiveSmallIntegerField()),
                ('reasons', models.JSONField(default=list)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['content_type', 'verdict', '-created_at'], name='analyzer_an_content_039242_idx')],
            },
        ),
    ]
