# Generated by Django 5.2.15 on 2026-06-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='module_title_ru',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module_title_uz',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
