# Generated by Django 5.2.15 on 2026-06-30 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils.text import slugify


def convert_existing_lessons_to_blocks(apps, schema_editor):
    Lesson = apps.get_model('courses', 'Lesson')
    LessonBlock = apps.get_model('courses', 'LessonBlock')

    for lesson in Lesson.objects.select_related('course').order_by('course_id', 'order', 'id'):
        base_slug = slugify(lesson.title_ru)[:120] or f"lesson-{lesson.order}"
        lesson_slug = base_slug
        suffix = 2
        while Lesson.objects.filter(course_id=lesson.course_id, slug=lesson_slug).exclude(id=lesson.id).exists():
            suffix_text = f"-{suffix}"
            lesson_slug = f"{base_slug[:140 - len(suffix_text)]}{suffix_text}"
            suffix += 1

        module_slug = slugify(lesson.module_title_ru)[:140] if lesson.module_title_ru else ""
        Lesson.objects.filter(id=lesson.id).update(slug=lesson_slug, module_slug=module_slug)

        if lesson.content_ru or lesson.content_uz:
            LessonBlock.objects.get_or_create(
                lesson_id=lesson.id,
                order=1,
                type="theory",
                defaults={
                    "title_ru": "Теория",
                    "title_uz": "Nazariya",
                    "body_ru": lesson.content_ru,
                    "body_uz": lesson.content_uz or lesson.content_ru,
                },
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_module_title_ru_lesson_module_title_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('theory', 'Theory'), ('definition', 'Definition'), ('example', 'Example'), ('warning', 'Warning'), ('note', 'Note'), ('code', 'Code'), ('checklist', 'Checklist'), ('task', 'Task'), ('quiz', 'Quiz'), ('materials', 'Materials')], max_length=24)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_uz', models.CharField(blank=True, max_length=200)),
                ('body_ru', models.TextField(blank=True)),
                ('body_uz', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LessonTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('checklist', 'Checklist'), ('sorting', 'Sorting'), ('scenario', 'Scenario')], default='text', max_length=24)),
                ('title_ru', models.CharField(max_length=200)),
                ('title_uz', models.CharField(blank=True, max_length=200)),
                ('instruction_ru', models.TextField()),
                ('instruction_uz', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module_slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lessonquestion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.lesson'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('course', 'slug'), name='unique_lesson_slug_per_course'),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='lessontask',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.lesson'),
        ),
        migrations.RunPython(convert_existing_lessons_to_blocks, noop_reverse),
    ]
