# Generated by Django 5.2.15 on 2026-06-19 08:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_ru', models.TextField()),
                ('text_uz', models.TextField()),
                ('category', models.CharField(choices=[('phishing', 'Phishing'), ('call', 'Fraudulent call'), ('sms', 'Fraudulent SMS'), ('malware', 'Malware'), ('social_engineering', 'Social engineering')], max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('explanation_ru', models.TextField()),
                ('explanation_uz', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_ru', models.CharField(max_length=300)),
                ('text_uz', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.question')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'O‘zbekcha')], max_length=5)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('expired', 'Expired')], default='started', max_length=12)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level', models.CharField(choices=[('none', 'Not passed'), ('basic', 'Basic'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='none', max_length=10)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('questions', models.ManyToManyField(through='quiz.SessionQuestion', to='quiz.question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='quiz.testsession'),
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.testsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'question'), name='one_answer_per_session_question')],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_question_per_quiz_session'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='unique_order_per_quiz_session'),
        ),
    ]
