# Generated by Django 5.2.15 on 2026-06-23 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='daily_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='kind',
            field=models.CharField(choices=[('standard', 'Standard'), ('daily', 'Daily')], default='standard', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='testsession',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'daily')), fields=('user', 'daily_date'), name='one_daily_quiz_per_user_date'),
        ),
    ]
