# Generated by Django 5.2.15 on 2026-06-23 05:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title_ru', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
                ('description_uz', models.TextField()),
                ('scam_type', models.CharField(max_length=40)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('order', 'title_ru'),
            },
        ),
        migrations.CreateModel(
            name='GameStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('message_ru', models.TextField()),
                ('message_uz', models.TextField()),
                ('tactic_ru', models.CharField(max_length=200)),
                ('tactic_uz', models.CharField(max_length=200)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='game.gamescenario')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'O‘zbekcha')], max_length=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=12)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('score_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('points_awarded', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='game.gamescenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.gamestep')),
            ],
        ),
        migrations.CreateModel(
            name='GameChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_ru', models.CharField(max_length=400)),
                ('text_uz', models.CharField(max_length=400)),
                ('feedback_ru', models.TextField()),
                ('feedback_uz', models.TextField()),
                ('points', models.SmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.gamestep')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='GameTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.gamechoice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='game.gamesession')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.gamestep')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gamestep',
            constraint=models.UniqueConstraint(fields=('scenario', 'order'), name='unique_game_step_order'),
        ),
        migrations.AddConstraint(
            model_name='gameturn',
            constraint=models.UniqueConstraint(fields=('session', 'step'), name='one_turn_per_game_step'),
        ),
    ]
