# Generated by Django 5.2.15 on 2026-06-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesession_ai_analysis_gamesession_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescenario',
            name='interface_type',
            field=models.CharField(choices=[('chat', 'Messenger chat'), ('call', 'Phone call'), ('website', 'Website')], default='chat', max_length=12),
        ),
    ]
